== Making an offer

'''

In tech hiring, you should always assume that you’re competing for the attention of any given candidate with a host of other companies who are just as determined as you are to hire the best people. This means that it should be your goal throughout this whole process to set yourself up to make a hire/not-hire decision as quickly as possible.

“Congratulations, we like you and want you to join our team” can be an awesome thing to hear after going through an interview process, but can also bring with it an interesting variety of follow-up questions, that if you’re not ready for can throw a rather large spanner in the works.

Remember that at the end of the day, you’re asking somebody to commit a large portion of their waking hours to your company and your mission for the foreseeable future, so you should be prepared to make sure that the person has access to as much information as possible so that they can make the best possible decision.

{nbsp} +

=== Pre-offer call

Telling somebody that you want them on your team is a big deal. Both parties have put in a lot of effort at this stage, so it makes sense to celebrate a bit - treat it like a victory lap. Like a lot of other important life events, this is news that deserves more than an email. Pick up the phone!

While delivering the good news, you’ll have a great opportunity to run them through the details of the offer and pre-empt any common questions: how many leave days are included, what kind of deductions can they expect on their payslip, potential start dates, etc. It’s really important to give the person a chance to ask any questions and to be very clear about when you’re expecting to receive a response.

{nbsp} +

=== Offer email

If for whatever reason you’re absolutely not able to contact somebody over the phone to tell them about an offer, you’ll need to adapt your strategy accordingly. Be as explicit in the email as possible about all of the information included in the offer and make sure that the person you’re making the offer to knows that you’d be more than happy to contact them to talk through the details.

Lines of communication need to be wide open at this stage of the process and if you’ve had to fall back on email for an offer, be sure to keep trying the phone until you get hold of them.

{nbsp} +

=== Testing the waters

From time to time we’ll see companies sending out thinly-veiled non-offers that typically adopt the format of “If we were to make you an offer, would you accept?”. A message like this can be confusing to receive, especially if you’ve already got an offer on the table from another company and can come off as extremely non-committal

While it’s understandable in the context of trying to avoid rejection, a general rule should be: if you’re in a position to make a hypothetical offer to somebody, you should also be in a position to make an actual one.

{nbsp} +

=== Contract

We’ve already established that you should be trying your best to get an offer in the hands of somebody who you want to hire in as little time as possible. Being able to do this quickly is the reason behind distinguishing between an offer letter and a contract, however if you can send somebody an actual employment contract in the same space of time as an offer, then it makes sense to do this.

The motivation behind this is mostly psychological; a contract can be seen as a bigger sign of commitment from a company than an offer letter (just remember to sign it before you send it through).

NOTE: *Protip:* If you know that you’re not going to be able to provide a contract super quickly, be upfront and say this rather than creating expectations for something that you can’t deliver.

{nbsp} +
