== Onboarding

'''

It’s done. It’s in the bag. Once the offer has been signed it’s all too easy to hang up your hiring hat, pat yourself on the back and wait until the person you just hired shows up for their first day of work before you speak to them again.

*This is an enormous mistake.* In reality, your onboarding process should start the second that the contract is signed. According to our data, one third of candidates who drop out before starting their new jobs, cite a lack of communication or miscommunication as a major contributing factor. You just spent an enormous chunk of time assessing this person and convincing them to join your team, don’t leave the door open to counter offers and cold feet by leaving them out of the loop now.

Your mindset at this stage of the process should be focussed on how you can keep somebody engaged in the time between them signing the employment contract and walking through the door on their first day. The best way to do this is by maintaining open and and proactive lines of

{nbsp} +

=== Welcome email

The simplest tactic here could be an email the day of or soon after they accept your offer or sign the contract. Ideally this email should come from somebody on the team that they’re going to be joining and should outline how stoked everyone is to have them on their team, as well as details like start date confirmation, what to bring with on their first day and what the best ways are to prepare so that they can hit the ground running.

{nbsp} +

=== Access to accounts

Once somebody has signed an employment contract, many companies will begin treating their new hires like fully fledged employees. Why not get them set up with their laptop and make sure they have access to all of the accounts that they’re going to be using on a daily basis. If you’re worried about giving somebody who isn’t settled in the building access to your entire code base, remember that it’s not an all or nothing decision. Give as much access as you’re comfortable with as early on as possible and take things from there.

If you use Slack and you haven’t already invited them as part of your interview/assessment process, now is a great time to get them set up. One fun side effect of this is that every time they get a slack notification from you, you’re going to be top of mind.

{nbsp} +

=== Moonlighting

We’ve seen companies assign paid work to a new hire as soon as they begin employment. As smart as it is to dial up the engagement to 11 in the time before somebody starts at your company, you still want to be mindful of the fact that they’re potentially still legally employed somewhere else.

Getting somebody to start working for you as soon as they’ve signed your contract regardless of current obligations might seem like a great way to keep a new hire engaged even before day one, however you do need to think about what problem it is that you’re trying to solve by using this approach. If you’re primarily concerned about staying top of mind, there are other way to accomplish that without potentially doubling somebody’s workload.
