== Team fit

'''

Team fit can be thought of as a subset of company culture, or depending how small your company is, the same thing altogether. The mindset behind these kinds of discussions tend to be more granular than determining alignment between a candidate’s career goals and a company’s mission, with more focus being put on smaller scale team dynamics.

TIP: *Protip:* You’ve spent a lot of time trying to hire the best possible team, why not show them off? Smart people tend to want to hang out and solve problems with other smart people, so showing that you can provide this kind of environment can be a super compelling reason to join a company.

{nbsp} +

=== Onsite chat

The easiest way to facilitate a team fit discussion is to literally just get the candidate in the same room as one or multiple members of the current team (this group should potentially include team leads or senior members) and get them to talk about whatever they find interesting. While getting people to talk is almost always educational, your goal in these discussions should be to drive the conversation towards what they look for in a team and how they tend to function best in a team environment.

{nbsp} +

=== Team drinks/dinner

If you really want to get a feel for somebody, put them at a dinner table with the rest of your team and let the conversation take its course. As an example, when OfferZen invites somebody for a simulation day for a Talent Advisor role, the whole TA team will often get together for a breakfast so that everybody can introduce themselves.

These kinds of engagements can give you a lot of opportunities to get to know somebody, as long as you’re careful to limit the scope of what you’re assessing to things that are relevant to your company and culture. You might find it strange that somebody dips their chips in their milkshake, but it’s definitely not a reason to turn somebody down at this stage of the hiring process.

{nbsp} +
