== Technical Assessment

'''

If your goal is to build a high quality product, everybody on your team should be up to snuff from a technical perspective. Anyone who isn’t pulling their weight can be a drain on the rest of team and will severely limit your ability to move quickly, which is why an effective technical assessment process is so important.

The question that you should be asking yourself when deciding on how to do this is “am I trying to filter people out, or am I assessing to find out what people’s strengths are?”. Sequencing also becomes a consideration at this point; an assessment that is administered closer to the beginning of the process should be designed to determine whether somebody possesses the baseline competencies that are necessary for them to perform well in a given role, while one that is carried out towards the end can be more focussed on confirming what a candidate’s strengths are in order to ensure that they are given work that engages them from day one.

Something that a lot of companies often forget at this stage, is just how competitive technical hiring can be. Any candidate that you’re talking to is most likely engaging with other companies as well and having a cumbersome, poorly designed technical assessment strategy is a good way to make sure that your process finds itself at the bottom of a candidate’s to-do list as they prioritise processes that are more respectful of their time.

Proper briefing is also super important when conducting any kind of technical assessment. A poorly briefed assessment project that you think shouldn’t take more than 4 hours, can end taking the whole weekend to complete if you’re not clear on exactly what the deliverables and goals of the project are.

{nbsp} +

=== Technical interview

This is potentially the most abstract of the options available to you when looking to assess technical ability. While it can be the most convenient from a candidate experience perspective, it’s also extremely reliant on the person running the interview being highly technical themselves.

The effectiveness of a technical interview hinges entirely on the strength of the questions that you ask as assessment tools. While it might feel good to ask a trick question that somebody outside of your building or specific might struggle to answer, you generally want to stick to questions that will allow candidates to showcase their own skill.

If you decide to adopt this strategy, it’s massively important that the interviewer has a good grasp of the problem that they’re asking the interviewee to solve. Somebody who doesn’t have a solid understanding of the problem themselves will struggle to move the discussion forward which will greatly limit the amount of information that you’re able to gather about somebody’s technical abilities.

{nbsp} +

=== Whiteboard

The classic combination of whiteboard and marker can be a really useful to tool to determine somebody’s technical capabilities, as long as you make sure to be extra clear up front on what it is you’re assessing. Presenting somebody with an empty whiteboard and telling them to start designing solutions can be stressful at the best of times and will probably not result in them putting down their best work.

The reality is that this kind of assessment is most effective at teasing out whether somebody can logically structure a solution to a given problem, which is something that should be made clear up front or even well in advance of the interview itself. Remember that your goal should be to assess somebody’s potential rather than ask them to showcase how well they can perform in a made-up test scenario; you’re conducting a technical assessment, not planning a technical ambush.

{nbsp} +

=== Paper programming

Similar to whiteboard assessments, a strategy that we sometimes see employed is asking somebody to complete a paper based coding test. While whiteboard assessments will typically involve a number of people looking at and discussing a problem, a paper based assessment lends itself more to the traditional paradigm of completing a test paper and handing it in, limiting the amount of insight that you’re able to obtain about how the candidate approached solving the problem at hand.

It’s possible to negate these drawbacks by taking time to ask the candidate to run you through the answers that they submitted, however at this point you might as well have used a whiteboard assessment making paper based tests hard to recommend as an efficient assessment mechanism.

{nbsp} +

=== Take home project

A take home project is exactly what it sounds like - a piece of work that you assign to a candidate to complete in their own time. As with all of the other types of assessment, it’s massively important to be explicit about what it is that you’re assessing, what the deliverables are and how long you expect somebody to set aside for the project.

A well briefed assessment project can easily be used as a jumping off point for a technical discussion during an interview. Getting somebody to talk you through their solution can be incredibly insightful and can tell you a great deal about their decision making and communication style.

Making sure that you assign projects that are relevant to the work your company does unlocks the additional benefit of giving the candidate a window into what to expect should they accept an offer of employment from you. If you’re trying to hire people who enjoy solving interesting problems, be sure to make the assessment you’re asking people to dedicate hours to as engaging and representative of an actual day’s work as possible.

{nbsp} +

=== Online test

If you’re trying to optimise your hiring process to be able to handle really high volumes of people, then an online test can be a good way to accomplish that. These kinds of assessments have the advantage of being able to be administered remotely, and are usually designed to be completed in the candidates own time within a specified time limit. This makes them much easier to fit into a schedule, provides a well defined block of time within which to focus while also preventing overly meticulous candidates from taking a weekend to complete what should be a 2 hour assessment.

The negative aspects of this approach are centred around the impersonal nature of the assessments and the way in which they’re deployed. If you decide to include this in your interview process, make sure that somebody takes ownership of it. It should be this person’s responsibility to maintain the integrity of the assessments (don’t send out the same test for months and years at a time, switch it up every now and then) while also moving people through the pipeline and being available as a human to talk to if the person taking the test has any questions.

Additionally, it’s worth mentioning that there will usually be costs involved in using an online code assessment service, either in the form of a subscription or per-use fee.

NOTE: The automatic scoring systems that many of these online testing tools use often lack the ability to pick up on nuance, meaning that smart developers often don’t get results that reflect their true ability. This can be counteracted by making it part of your process for a human to review the code that gets submitted.

{nbsp} +

=== Pair programming

A pair programming assessment involves assigning somebody from your existing team sitting with and collaborating (either remotely, or by physically sitting at the same workstation) to solve a single problem. This technique can an extremely effective way to gauge a number of key metrics, from technical ability and problem solving skills, through to communication ability and collaboration. It does however come at a significant cost in terms of preparation and the involvement of multiple members of your existing team, so it’s not to be undertaken lightly.

A common theme so far has been that briefing is critical to an effective technical assessment, and pair programming is no different. Well executed pair programming assessments will always be explicit up-front about the differentiation between the assessors and the people that the candidate will be programming with. Poorly run pair programming sessions can easily result in a candidate being hesitant to explore all of the solutions at their disposal, which is understandable when you consider how easy it is to feel like the person sitting next to you is judging your every keystroke.

{nbsp} +

=== Nothing

While doing nothing is always an option, it is very seldom the most effective one. One bad hire early on can do a lot to kneecap your ability to hit product roadmap goals, not to mention the potential cascading negative effects on your company culture.

You might be saving time in the short term by relying solely on your finely honed intuition, but we strongly recommend doing some form of due diligence to ensure that the person that you’re adding to your team is able to contribute meaningfully, shore up existing weakness and help you build an awesome product and team.

{nbsp} +
